version: "3.7"
services:
    dashboard:
        image: phpmate
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - composer
        ports:
            - 8080:8080
        command: [ "php", "-S", "0.0.0.0:8080", "-t", "public" ]

    php:
        image: phpmate
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - composer

    composer:
        image: phpmate
        build:
            context: .
            target: dev
        volumes:
            - .:/var/www
        working_dir: /var/www
        entrypoint: "composer"
        command: [ "install", "--no-interaction" ]
