version: "3.7"
services:
    dashboard:
        image: phpmate
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - composer
            - postgres
        ports:
            - 8080:8080
        entrypoint: [ "bash", "/docker-entrypoint.sh" ]
        command: [ "php", "-S", "0.0.0.0:8080", "-t", "public" ]

    js-watch:
        image: node:14
        volumes:
            - .:/var/www
        working_dir: /var/www
        restart: unless-stopped
        entrypoint: [""]
        command: "bash -c 'yarn install && yarn run watch'"

    postgres:
        # alpine is forbidden => https://stackoverflow.com/questions/58135353/postgres-seems-to-be-ignoring-my-default-collation
        image: postgres:13
        environment:
            POSTGRES_USER: phpmate
            POSTGRES_PASSWORD: phpmate
        volumes:
            - .docker-data/postgres:/var/lib/postgresql/data
        ports:
            - "${PHPMATE_POSTGRES_PORT:-5432}:5432"

    # Helper service
    composer:
        image: phpmate
        build:
            context: .
            target: dev
        volumes:
            - .:/var/www
        working_dir: /var/www
        entrypoint: "composer"
        command: [ "install", "--no-interaction" ]

    worker:
        image: phpmate
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - dashboard
        command: [ "wait-for-it", "dashboard:8080", "--", "bin/worker" ]

    scheduler:
        image: phpmate
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - dashboard
        command: [ "wait-for-it", "dashboard:8080", "--", "bin/scheduler" ]
