version: "3.7"
services:
    php:
        image: phpmate
        build: .
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - composer

    composer:
        image: phpmate
        build: .
        volumes:
            - .:/var/www
        working_dir: /var/www
        entrypoint: "composer"
        command: [ "install", "--no-interaction" ]
