version: "3.7"
services:
    dashboard:
        image: phpmate
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - composer
            - mariadb
        ports:
            - 8080:8080
        entrypoint: [ "bash", "/docker-entrypoint.sh" ]
        command: [ "php", "-S", "0.0.0.0:8080", "-t", "public" ]

    mariadb:
        image: mariadb:10.6.4
        volumes:
            - .docker-data/mariadb/:/var/lib/mysql
        environment:
          MARIADB_DATABASE: phpmate
          MARIADB_USER: phpmate
          MARIADB_PASSWORD: phpmate
          MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
        restart: unless-stopped
        ports:
          - "${PHPMATE_DB_PORT:-3306}:3306"

    # Helper service
    composer:
        image: phpmate
        build:
            context: .
            target: dev
        volumes:
            - .:/var/www
        working_dir: /var/www
        entrypoint: "composer"
        command: [ "install", "--no-interaction" ]

    worker:
        image: phpmate
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - dashboard
        command: [ "wait-for-it", "dashboard:8080", "--", "bin/worker" ]

    scheduler:
        image: phpmate
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - dashboard
        command: [ "wait-for-it", "dashboard:8080", "--", "bin/scheduler" ]
