version: "3.7"
services:
    dashboard:
        image: ghcr.io/peon-dev/php:main
        volumes:
            - .:/peon
            - .docker/entrypoints:/docker-entrypoint.d
        working_dir: /peon
        depends_on:
            - composer
            - postgres
            - mercure
        ports:
            - "${PEON_DASHBOARD_PORT:-8080}:8080"

    js-watch:
        image: node:14
        volumes:
            - .:/peon
        working_dir: /peon
        restart: unless-stopped
        entrypoint: [""]
        command: "bash -c 'yarn install && yarn run watch'"

    postgres:
        # alpine is forbidden => https://stackoverflow.com/questions/58135353/postgres-seems-to-be-ignoring-my-default-collation
        image: postgres:13
        environment:
            POSTGRES_USER: peon
            POSTGRES_PASSWORD: peon
        volumes:
            - .docker-data/postgres:/var/lib/postgresql/data
        ports:
            - "${PEON_POSTGRES_PORT:-5432}:5432"

    # Helper service
    composer:
        image: ghcr.io/peon-dev/php:main
        volumes:
            - .:/peon
            - .docker/entrypoints:/docker-entrypoint.d
        working_dir: /peon
        entrypoint: "composer"
        command: [ "install", "--no-interaction" ]

    worker:
        image: ghcr.io/peon-dev/php:main
        volumes:
            - .:/peon
            - /var/run/docker.sock:/var/run/docker.sock
            - $PWD/var/working_directories:/peon/var/working_directories
        environment:
            HOST_WORKING_DIRECTORIES_PATH: $PWD/var/working_directories
        working_dir: /peon
        depends_on:
            - dashboard
        command: [ "wait-for-it", "dashboard:8080", "--", "bin/worker" ]

    scheduler:
        image: ghcr.io/peon-dev/php:main
        volumes:
            - .:/peon
        working_dir: /peon
        depends_on:
            - dashboard
        command: [ "wait-for-it", "dashboard:8080", "--", "bin/scheduler" ]

    adminer:
        image: adminer:4.8.0
        ports:
            - "${PEON_ADMINER_PORT:-8000}:8080"
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        depends_on:
            - postgres

    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
            # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins *
        # Comment the following line to disable the development mode
        command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
        volumes:
            - .docker-data/mercure_data:/data
            - .docker-data/mercure_config:/config
        ports:
          - "${PEON_MERCURE_PORT:-8180}:80"
