name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: 7.4
            coverage: none # default is xdebug
            extensions: mbstring # needed by phpunit

      -   run: composer install --no-progress

      -   run: vendor/bin/phpunit tests


  phpstan:
      runs-on: ubuntu-latest
      steps:
        -   uses: actions/checkout@v2
        -   uses: shivammathur/setup-php@v2
            with:
              php-version: 7.4
              coverage: none # default is xdebug
              extensions: mbstring # needed by phpunit

        -   run: composer install --no-progress

        -   run: vendor/bin/phpstan src tests
