name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: 8.0
            coverage: none # default is xdebug
            extensions: mbstring # needed by phpunit

      -   run: composer install --dev --no-progress

      -   env:
              TEST_GITLAB_PERSONAL_ACCESS_TOKEN: ${{ secrets.TEST_GITLAB_PERSONAL_ACCESS_TOKEN }}
              TEST_GITLAB_USERNAME: ${{ secrets.TEST_GITLAB_USERNAME }}
          run: vendor/bin/phpunit


  phpstan:
      runs-on: ubuntu-latest
      steps:
        -   uses: actions/checkout@v2
        -   uses: shivammathur/setup-php@v2
            with:
              php-version: 8.0
              coverage: none # default is xdebug
              extensions: mbstring # needed by phpunit

        -   run: composer install --dev --no-progress

        -   run: composer run-script phpstan
