name: Tests

on:
    push:
    pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
        DATABASE_URL: postgresql://peon:peon@127.0.0.1:5432/peon?serverVersion=13&charset=utf8

    services:
      db:
          image: postgres:13
          env:
              POSTGRES_USER: peon
              POSTGRES_PASSWORD: peon
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
          ports:
              - 5432:5432

    steps:
      -   uses: actions/checkout@v2
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: 8.1
            coverage: none # default is xdebug
            extensions: mbstring, uuid # needed by phpunit

      -   run: composer install --dev --no-progress
      -   run: yarn install
      -   run: yarn run dev

      -   env:
              TEST_GITLAB_PERSONAL_ACCESS_TOKEN: ${{ secrets.TEST_GITLAB_PERSONAL_ACCESS_TOKEN }}
              TEST_GITLAB_USERNAME: ${{ secrets.TEST_GITLAB_USERNAME }}
              TEST_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.TEST_GITHUB_PERSONAL_ACCESS_TOKEN }}
              TEST_GITHUB_USERNAME: ${{ secrets.TEST_GITHUB_USERNAME }}
              HOST_WORKING_DIRECTORIES_PATH: ${{ github.workspace }}/var/working_directories
          run: vendor/bin/phpunit


  phpstan:
      runs-on: ubuntu-latest
      steps:
        -   uses: actions/checkout@v2
        -   uses: shivammathur/setup-php@v2
            with:
              php-version: 8.1
              coverage: none # default is xdebug
              extensions: mbstring, uuid # needed by phpunit

        -   run: composer install --dev --no-progress

        -   run: composer run-script phpstan


  migrations-up-to-date:
      runs-on: ubuntu-latest
      env:
        DATABASE_URL: postgresql://peon:peon@127.0.0.1:5432/peon?serverVersion=13&charset=utf8

      services:
        db:
            image: postgres:13
            env:
                POSTGRES_USER: peon
                POSTGRES_PASSWORD: peon
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
            ports:
                - 5432:5432

      steps:
        -   uses: actions/checkout@v2
        -   uses: shivammathur/setup-php@v2
            with:
              php-version: 8.1
              coverage: none # default is xdebug
              extensions: mbstring, uuid # needed by phpunit

        -   run: composer install --dev --no-progress

        -   run: bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
        -   run: bin/console doctrine:schema:update --dump-sql
        -   run: bin/console doctrine:schema:validate
